### ISSUE TITLE
Django runserver throws AttributeError on closing

### ISSUE THREAD

**Issue by slimadvies** [valkey-io/valkey-py#158] opened 2024-12-18 13:36 UTC
When closing django-admin runserver, Valkey client consistently throws an attribute exception.

This is the same issue as https://github.com/redis/redis-py/issues/3014

My setup:
Macos 15.2
Python 3.13.1
Django 4.2.17
Valkey-py 6.0.2

$ django-admin runserver

December 18, 2024 - 14:31:26
Django version 4.2.17, using settings 'milieubarometer_conf.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

^CException ignored in: <function Valkey.__del__ at 0x106c76a20>
Traceback (most recent call last):
  File ".../lib/python3.13/site-packages/valkey/client.py", line 521, in __del__
  File ".../site-packages/valkey/client.py", line 536, in close
  File ".../lib/python3.13/site-packages/valkey/connection.py", line 1179, in disconnect
  File ".../lib/python3.13/site-packages/valkey/connection.py", line 1083, in _checkpid
AttributeError: 'NoneType' object has no attribute 'getpid'

**Comment by amirreza8002** [comment] 2024-12-18 13:38
hi
can you show the code that is using valkey?

**Comment by spyinx** [comment] 2024-12-18 14:47
@amirreza8002 it's easy to reproduce:
```shell
>>> from valkey.client import Valkey
>>> r = Valkey(host="127.0.0.1", port=6379)
>>> exit()
Exception ignored in: <function Valkey.__del__ at 0x7efcc1b28900>
Traceback (most recent call last):
  File "/root/valkey-learning/valkey-py-6.0.2/valkey/client.py", line 521, in __del__
  File "/root/valkey-learning/valkey-py-6.0.2/valkey/client.py", line 536, in close
  File "/root/valkey-learning/valkey-py-6.0.2/valkey/connection.py", line 1180, in disconnect
  File "/root/valkey-learning/valkey-py-6.0.2/valkey/connection.py", line 1084, in _checkpid
TypeError: 'NoneType' object is not callable
(env-3.13) [root@spyinx valkey-py-6.0.2]# 
```
just use valkey-py in a subprocess, like python shell et.

**Comment by amirreza8002** [comment] 2024-12-18 14:51
hi
perhaps, but I'm more interested in the django part, how is valkey used in django in this context? 
i use valkey with django and it exits cleanly 

since i maintain django-valkey, i would want to know if there's a problem

**Comment by mkmkme** [comment] 2024-12-18 14:52
@spyinx I couldn't reproduce this on my machine (Linux). What setup do you have?

**Comment by mkmkme** [comment] 2024-12-18 15:00
Interestingly enough, it doesn't occur in `ipython` (which I mainly use), but does appear in regular `python` repl

**Comment by amirreza8002** [comment] 2024-12-18 15:01
hi
i can reproduce it with main
```
>>> from valkey import Valkey
>>> v = Valkey()
>>> exit()
Exception ignored in: <function Valkey.__del__ at 0x770a28e55300>
Traceback (most recent call last):
  File "/home/amirreza/projects/valkey-py/valkey/client.py", line 521, in __del__
  File "/home/amirreza/projects/valkey-py/valkey/client.py", line 536, in close
  File "/home/amirreza/projects/valkey-py/valkey/connection.py", line 1179, in disconnect
  File "/home/amirreza/projects/valkey-py/valkey/connection.py", line 1083, in _checkpid
TypeError: 'NoneType' object is not callable
```

but i'd like to emphsis that i've never seen the django one

**Comment by amirreza8002** [comment] 2024-12-18 15:01
> Interestingly enough, it doesn't occur in `ipython` (which I mainly use), but does appear in regular `python` repl

bpython also exits cleanly, i just saw

**Comment by mkmkme** [comment] 2024-12-18 15:06
Thanks @amirreza8002 ! Can confirm it doesn't fail on Python 3.12.

I will start investigating now and hopefully will come up with a solution soon.

**Comment by spyinx** [comment] 2024-12-18 15:07
yes, only python3.13 has the same problem, i used both versions in python3.12, it's ok

**Comment by mkmkme** [comment] 2024-12-18 15:13
Just a small note for everyone in this thread: valkey-py 6.0.2 doesn't yet officially support Python 3.13.

We have 6.1.0b1 with Python 3.13 support, but clearly it is affected by the same issue.

Thank you everyone for drawing attention to this, it should be fixed in stable 6.1.0

**Comment by amirreza8002** [comment] 2024-12-18 15:16
for what it's worth, about the issue itself, i just tested django + valkey in python3.13 and did **not** have this issue
i checked both `runserver` and django shell

**Comment by mkmkme** [comment] 2024-12-18 15:19
Yeah I'm not sure what setup @slimadvies is using, but my guess is that when we fix it for just Python subprocess, it'll be fixed for them as well.

**Comment by slimadvies** [comment] 2024-12-19 08:00
Thanks. This should fix it. Nice investigating. 👍

**Comment by mkmkme** [comment] 2024-12-20 08:40
Got the same issue while testing the sentinel code, will have to fix it as well.

**Closed** 2024-12-24 08:46 UTC
Labels: bug
